CREATE DATABASE IF NOT EXISTS gestion_dons;
USE gestion_dons;

CREATE TABLE gd_regions(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE gd_villes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idRegion INT NOT NULL,
    nomVille VARCHAR(100) NOT NULL,
    FOREIGN KEY (idRegion) REFERENCES gd_regions(id)
);

CREATE TABLE gd_typesDons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE gd_besoinVille (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idVille INT NOT NULL,
    idDon INT NOT NULL,
    qte DECIMAL(15,2) NOT NULL,
    daty TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idVille) REFERENCES gd_villes(id),
    FOREIGN KEY (idDon) REFERENCES gd_dons(id)
);

CREATE TABLE gd_dons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    libelle VARCHAR(255),
    pu DECIMAL(15,2) NOT NULL,
    idTypes INT NOT NULL,
    daty TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idTypes) REFERENCES gd_typesDons(id)
);

CREATE TABLE gd_stock (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idDon INT NOT NULL,
    qte DECIMAL(15,2) NOT NULL,
    daty TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idDon) REFERENCES gd_dons(id)
);

CREATE TABLE gd_mvstock (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idbesoin INT NOT NULL,
    idstock INT NOT NULL,
    entree DECIMAL(15,2) NOT NULL,
    sortie DECIMAL(15,2) NOT NULL,
    daty TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    designation VARCHAR(255),
    FOREIGN KEY (idbesoin) REFERENCES gd_besoinVille(id),
    FOREIGN KEY (idstock) REFERENCES gd_stock(id)
);

